In [327]:
import numpy as np
from numpy import linalg as LA

In [328]:
def jacobi_solve(B, c, eps):

    n = 0
    size = len(A)
    q = LA.norm(B, ord=np.inf)
    stop = (1 - q) / q * eps
    
    x = c.copy()
    
    while True:
        x_old = x.copy()
        x = c + B@x
        n += 1
        
        if LA.norm(x - x_old) <= stop:
            return x, n

In [329]:
def gauss_seidel_solve(B, c, eps):
    
    n = 0
    q = LA.norm(B, ord=np.inf)
    stop = (1 - q) / q * eps
    
    x = c.copy()
    
    while True:
        x_old = x.copy()
        
        for i in range(size): x[i] = B[i] @ x + c[i]
        n += 1
        
        if LA.norm(x - x_old) <= stop:
            return x, n

In [330]:
def relax_solve(B, c, q):
    
    s = np.max(np.abs(LA.eig(B)[1]))
    n = 0
    w = 1 / (1 + np.sqrt(1 - s**2))
    q = LA.norm(B, ord=np.inf)
    stop = (1 - q) / q * eps
    x = c.copy()

    while True:
        x_old = x.copy()
        
        for i in range(size):
            x[i] = B[i] @ x + c[i]
            x[i] = x[i]*w + (1 - w) * x_old[i]
                
        n += 1
        
        if LA.norm(x - x_old) <= stop:
            return x, n

In [331]:
size = 18
eps = 1e-05

In [332]:
a = np.arange(1, size+1)
A = np.array([a * np.concatenate((np.ones(i)*-1, np.ones(size-i))) for i in range(size)], dtype=float)
b = np.arange(1, size+1, dtype=float)
A[range(size), range(size)] = 330
# A[0, 0] = 1

# A[1:] = A[1:] + A[0]
# b[1:] = b[1:] + b[0]

# for row1 in range(size-1, 0, -1):
#     for row2 in range(row1-1, -1, -1):
#         A[row2] = A[row2] - A[row1]*A[row2, row1]/A[row1, row1]
#         b[row2] = b[row2] - b[row1]**A[row2, row1]/A[row1, row1]
    

# A = np.diag(A[range(size), range(size)])

In [333]:
A

array([[330.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1., 330.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2., 330.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2.,  -3., 330.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2.,  -3.,  -4., 330.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2.,  -3.,  -4.,  -5., 330.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2.,  -3.,  -4.,  -5.,  -6., 330.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7., 330.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],


In [334]:
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

In [335]:
B = np.array([-A[i]/A[i, i] for i in range(size)])
B[range(size), range(size)] = 0

c = np.array([b[i]/A[i, i] for i in range(size)])

In [336]:
np.round(B, 3)

array([[ 0.   , -0.006, -0.009, -0.012, -0.015, -0.018, -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.052, -0.055],
       [ 0.003,  0.   , -0.009, -0.012, -0.015, -0.018, -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.052, -0.055],
       [ 0.003,  0.006,  0.   , -0.012, -0.015, -0.018, -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.052, -0.055],
       [ 0.003,  0.006,  0.009,  0.   , -0.015, -0.018, -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.052, -0.055],
       [ 0.003,  0.006,  0.009,  0.012,  0.   , -0.018, -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.052, -0.055],
       [ 0.003,  0.006,  0.009,  0.012,  0.015,  0.   , -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.

In [337]:
np.round(c, 3)

array([0.003, 0.006, 0.009, 0.012, 0.015, 0.018, 0.021, 0.024, 0.027,
       0.03 , 0.033, 0.036, 0.039, 0.042, 0.045, 0.048, 0.052, 0.055])

In [338]:
norm_B = LA.norm(B, ord='fro')
norm_c = LA.norm(c)
# k = np.log(np.e * (1 - norm_B) / norm_c) / np.log(norm_B)
k = np.log(eps / (norm_c + norm_c / (1 - norm_B))) / np.log(norm_B)
k, norm_B, norm_c

(19.34946009709336, 0.5737844979935769, 0.13916318185703072)

In [339]:
x_appr, n = jacobi_solve(B, c, eps)
x_appr, n

(array([-0.0129698 , -0.01003962, -0.007135  , -0.00422067, -0.00126056,
         0.00178314,  0.00495098,  0.00828731,  0.01184158,  0.0156698 ,
         0.01983627,  0.02441573,  0.02949591,  0.03518074,  0.0415942 ,
         0.04888528,  0.05723407,  0.06685949]),
 9)

In [340]:
x_appr, n = gauss_seidel_solve(B, c, eps)
x_appr, n

(array([-0.01296956, -0.0100394 , -0.00713479, -0.0042205 , -0.00126044,
         0.00178321,  0.00495097,  0.00828721,  0.01184138,  0.01566948,
         0.01983583,  0.02441517,  0.02949525,  0.03517999,  0.04159341,
         0.04888449,  0.05723335,  0.0668589 ]),
 6)

In [341]:
relax_solve(B, c, eps)

(array([-0.01296973, -0.0100396 , -0.00713505, -0.00422082, -0.00126084,
         0.00178271,  0.00495038,  0.00828654,  0.01184064,  0.0156687 ,
         0.01983507,  0.0244145 ,  0.02949476,  0.03517976,  0.04159349,
         0.04888484,  0.05723367,  0.06685842]),
 10)

In [342]:
x = LA.solve(A, b)
x

array([-0.01296935, -0.01003919, -0.00713459, -0.00422031, -0.00126025,
        0.00178338,  0.00495113,  0.00828736,  0.01184152,  0.01566961,
        0.01983595,  0.02441528,  0.02949535,  0.03518008,  0.04159349,
        0.04888456,  0.05723341,  0.06685896])