In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
def jacobi_solve(B, c, eps):

    n = 0
    size = len(A)
    q = LA.norm(B)
    stop = (1 - q) / q * eps
    
    x = c.copy()
    
    while True:
        x_old = x.copy()
        x = c + B@x
        n += 1
        
        if LA.norm(x - x_old) <= stop:
            return x, n

In [3]:
def gauss_seidel_solve(B, c, A, eps):
    
    U = np.triu(A,1)
    L = np.tril(A,-1)
    D = np.tril(np.triu(A))    
    n = 0
    LDInvU = LA.inv(L+D)@U
    LDInvb = LA.inv(L+D)@b
    t = LA.norm(LA.inv(L+D)@U)
    stop = (1 - t) / t * eps
    
    x = c.copy()
    
    while True:
        
        x_old = x.copy()
#         for i in range(size): x[i] = B[i] @ x + c[i]
        x = -LDInvU@x + LDInvb
        n += 1
        
        if LA.norm(x - x_old) <= stop:
            return x, n

In [4]:
def relax_solve(B, c, eps, w=None):
    
    U = np.triu(A,1)
    L = np.tril(A,-1)
    D = np.tril(np.triu(A))
    t = LA.norm(LA.inv(L+D)@U)
    stop = (1 - t) / t * eps
    
    if w is None:
        s = np.max(np.abs(LA.eig(B)[1]))
        w = 2 / (1 + np.sqrt(1 - s**2))
        
    n = 0    
    x, x_old = c.copy(), c.copy()

    while True:
        x_old = x.copy()
        
        for i in range(size):
            x[i] = B[i] @ x + c[i]
            x[i] = x_old[i]*(1-w) + x[i]*w
        n += 1
        
        if LA.norm(x - x_old) <= stop:
            return x, n

In [5]:
size = 18
eps = 1e-5

In [6]:
a = np.arange(1, size+1)
A = np.array([a * np.concatenate((np.ones(i)*-1, np.ones(size-i))) for i in range(size)], dtype=float)
b = np.arange(1, size+1, dtype=float)
A[range(size), range(size)] = 330


# A[0, 0] = 1

# A[1:] = A[1:] + A[0]
# b[1:] = b[1:] + b[0]

# for row1 in range(size-1, 0, -1):
#     for row2 in range(row1-1, -1, -1):
#         A[row2] = A[row2] - A[row1]*A[row2, row1]/A[row1, row1]
#         b[row2] = b[row2] - b[row1]**A[row2, row1]/A[row1, row1]
    

# A = np.diag(A[range(size), range(size)])

In [7]:
A

array([[330.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1., 330.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2., 330.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2.,  -3., 330.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2.,  -3.,  -4., 330.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2.,  -3.,  -4.,  -5., 330.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2.,  -3.,  -4.,  -5.,  -6., 330.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7., 330.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],


In [8]:
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

In [9]:
B = np.array([-A[i]/A[i, i] for i in range(size)])
B[range(size), range(size)] = 0

c = np.array([b[i]/A[i, i] for i in range(size)])

In [10]:
np.round(B, 3)

array([[ 0.   , -0.006, -0.009, -0.012, -0.015, -0.018, -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.052, -0.055],
       [ 0.003,  0.   , -0.009, -0.012, -0.015, -0.018, -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.052, -0.055],
       [ 0.003,  0.006,  0.   , -0.012, -0.015, -0.018, -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.052, -0.055],
       [ 0.003,  0.006,  0.009,  0.   , -0.015, -0.018, -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.052, -0.055],
       [ 0.003,  0.006,  0.009,  0.012,  0.   , -0.018, -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.052, -0.055],
       [ 0.003,  0.006,  0.009,  0.012,  0.015,  0.   , -0.021, -0.024,
        -0.027, -0.03 , -0.033, -0.036, -0.039, -0.042, -0.045, -0.048,
        -0.

In [11]:
np.round(c, 3)

array([0.003, 0.006, 0.009, 0.012, 0.015, 0.018, 0.021, 0.024, 0.027,
       0.03 , 0.033, 0.036, 0.039, 0.042, 0.045, 0.048, 0.052, 0.055])

In [12]:
x = LA.solve(A, b)
x

array([-0.01296935, -0.01003919, -0.00713459, -0.00422031, -0.00126025,
        0.00178338,  0.00495113,  0.00828736,  0.01184152,  0.01566961,
        0.01983595,  0.02441528,  0.02949535,  0.03518008,  0.04159349,
        0.04888456,  0.05723341,  0.06685896])

In [13]:
norm_B = LA.norm(B)
norm_c = LA.norm(c)
# k = np.log(np.e * (1 - norm_B) / norm_c) / np.log(norm_B)
k = np.log(eps / (norm_c + norm_c / (1 - norm_B))) / np.log(norm_B)
k, norm_B, norm_c

(19.34946009709336, 0.5737844979935769, 0.13916318185703072)

In [14]:
x_appr_jac, n = jacobi_solve(B, c, eps)
x_appr_jac

array([-0.01296954, -0.01003939, -0.00713479, -0.00422051, -0.00126047,
        0.00178315,  0.0049509 ,  0.00828713,  0.01184129,  0.01566938,
        0.01983574,  0.02441509,  0.0294952 ,  0.03517998,  0.04159345,
        0.04888459,  0.05723351,  0.06685912])

In [15]:
LA.norm(x_appr_jac - x), n

(7.898513734500816e-07, 10)

In [16]:
U = np.triu(A,1)
L = np.tril(A,-1)
D = np.tril(np.triu(A))

t = LA.norm(LA.inv(L+D)@U)

x0 = c
x1 = x0.copy()
for i in range(size): x1[i] = B[i] @ x1 + c[i]

np.log(eps*(1-t)/LA.norm(x1-x0))/np.log(t), t

(16.81934390995068, 0.5651783007799079)

In [17]:
x_appr_gau, n = gauss_seidel_solve(B, c, A, eps)
x_appr_gau

array([-0.01296956, -0.0100394 , -0.00713479, -0.0042205 , -0.00126044,
        0.00178321,  0.00495097,  0.00828721,  0.01184138,  0.01566948,
        0.01983583,  0.02441517,  0.02949525,  0.03517999,  0.04159341,
        0.04888449,  0.05723335,  0.0668589 ])

In [18]:
LA.norm(x_appr_gau - x), n

(6.069411855623665e-07, 6)

In [19]:
x_appr_rel, n = relax_solve(B, c, eps, 0.9)
x_appr_rel

array([-0.01296914, -0.01003897, -0.00713437, -0.00422008, -0.00126003,
        0.00178359,  0.00495131,  0.0082875 ,  0.01184159,  0.0156696 ,
        0.01983586,  0.02441512,  0.02949516,  0.03517993,  0.04159345,
        0.04888471,  0.05723365,  0.06685884])

In [20]:
LA.norm(x_appr_rel - x), n

(7.337640381373529e-07, 5)

$$k \leq \frac{ln(\frac{\mathcal{E}(1-t)}{\lVert x^1 - x^0 \rVert})}{ln(t)}$$