In [383]:
import numpy as np
from numpy import linalg as LA

In [384]:
def jacobi_solve(B, c, eps):

    n = 0
    size = len(A)
    q = LA.norm(B, ord=np.inf)
    stop = (1 - q) / q * eps
    
    x = c.copy()
    
    while True:
        x_old = x.copy()
        x = c + B@x
        n += 1
        
        if LA.norm(x - x_old) <= stop:
            return x, n

In [385]:
def gauss_seidel_solve(B, c, eps):
    
    n = 0
    q = LA.norm(B, ord=np.inf)
    stop = (1 - q) / q * eps
    
    x = c.copy()
    
    while True:
        x_old = x.copy()
        
        for i in range(size): x[i] = B[i] @ x + c[i]
        n += 1
        
        if LA.norm(x - x_old) <= stop:
            return x, n

In [386]:
size = 5

In [437]:
a = np.arange(1, size+1)
A = np.array([a * np.concatenate((np.ones(i)*-1, np.ones(size-i))) for i in range(size)], dtype=float)
A[range(size), range(size)] = 0
A[0, 0] = 1

A[1:] = A[1:] + A[0]

# for col in range(size-1):
#     for j in range(col+1, size-2):
#         A[:, j] -= A[:, col] * A[j, j]
        

# b = np.arange(1, size+1, dtype=float)
# A = np.roll(A, -1, axis=1)
# b = np.roll(b, -1)

In [438]:
A

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 0.,  2.,  6.,  8., 10.],
       [ 0.,  0.,  3.,  8., 10.],
       [ 0.,  0.,  0.,  4., 10.],
       [ 0.,  0.,  0.,  0.,  5.]])

In [377]:
b

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18.,  1.])

In [378]:
B = np.array([-A[i]/A[i, i] for i in range(size)])
B[range(size), range(size)] = 0

c = np.array([b[i]/A[i, i] for i in range(size)])

In [379]:
np.round(B, 3)

array([[  0.   ,  -2.   ,  -3.   ,  -4.   ,  -5.   ,  -6.   ,  -7.   ,
         -8.   ,  -9.   , -10.   , -11.   , -12.   , -13.   , -14.   ,
        -15.   , -16.   , -17.   , -18.   ],
       [ -0.   ,   0.   ,  -3.   ,  -4.   ,  -5.   ,  -6.   ,  -7.   ,
         -8.   ,  -9.   , -10.   , -11.   , -12.   , -13.   , -14.   ,
        -15.   , -16.   , -17.   , -18.   ],
       [ -0.   ,  -0.   ,   0.   ,  -2.667,  -3.333,  -4.   ,  -4.667,
         -5.333,  -6.   ,  -6.667,  -7.333,  -8.   ,  -8.667,  -9.333,
        -10.   , -10.667, -11.333, -12.   ],
       [ -0.   ,  -0.   ,  -0.   ,   0.   ,  -2.5  ,  -3.   ,  -3.5  ,
         -4.   ,  -4.5  ,  -5.   ,  -5.5  ,  -6.   ,  -6.5  ,  -7.   ,
         -7.5  ,  -8.   ,  -8.5  ,  -9.   ],
       [ -0.   ,  -0.   ,  -0.   ,  -0.   ,   0.   ,  -2.4  ,  -2.8  ,
         -3.2  ,  -3.6  ,  -4.   ,  -4.4  ,  -4.8  ,  -5.2  ,  -5.6  ,
         -6.   ,  -6.4  ,  -6.8  ,  -7.2  ],
       [ -0.   ,  -0.   ,  -0.   ,  -0.   ,  -0.   ,   0.   ,  -2

In [380]:
np.round(c, 3)

array([1.   , 1.5  , 1.333, 1.25 , 1.2  , 1.167, 1.143, 1.125, 1.111,
       1.1  , 1.091, 1.083, 1.077, 1.071, 1.067, 1.062, 1.059, 0.056])

In [381]:
norm_B = LA.norm(B, ord='fro')
norm_c = LA.norm(c)
# k = np.log(np.e * (1 - norm_B) / norm_c) / np.log(norm_B)
k = np.log(0.001 / (norm_c + norm_c / (1 - norm_B))) / np.log(norm_B)
k, norm_B, norm_c

(-1.9144599365353685, 82.64650405519583, 4.740252968575838)

In [382]:
x_appr, n = jacobi_solve(B, c, 0.001)
x_appr, n

KeyboardInterrupt: 

In [ ]:
x_appr, n = gauss_seidel_solve(B, c, 0.001)
x_appr, n

In [ ]:
x = LA.solve(A, b)
x

In [ ]:
x - x_appr