In [443]:
import numpy as np
from scipy import linalg as LA
from scipy.linalg import hessenberg as scipy_hessenberg

In [444]:
f_name = 'matrix.txt'

def mout(m):
    print(np.round(m, 2))

In [445]:
def parse_matrix(f_name=f_name):
    with open(f_name, 'r') as f:
            matrix = f.read().split('\n')
            matrix = list(map(lambda row: row.split(' '), matrix))
            return np.array(matrix, dtype=np.float64), len(matrix)

In [446]:
def hessenberg(A):
    n = len(A)
    w = np.zeros((n, n - 2))
    s = np.zeros(n - 2)
    m = np.zeros(n - 2)
    a = A.copy()
    for j in range(n - 2):
        sum1 = 0
        for k in range(j+1, n):
            sum1 += a[k, j]**2
            
        s[j] = np.sign(-a[j + 1, j]) * np.sqrt(sum1)

        if s[j] == 0:
            m[j] = 0
        else:
            m[j] = 1 / np.sqrt(2 * s[j]**2 - 2 * s[j] * a[j + 1, j])

        w[j + 1, j] = a[j + 1, j] - s[j]
        
        for i in range(j + 2, n):
            w[i, j] = a[i, j]
            
        H = np.eye(n) - 2 * (m[j]**2) * np.outer(w[:,j], w[:,j])
        a = H @ a @ H

    return a

In [447]:
def get_eig_vals(A):
    A = A.astype(np.complex64)
    a, b, c, d = A[0, 0], A[0, 1], A[1, 0], A[1, 1]

    x1 = 0.5 * (a + d + np.sqrt((a+d)**2 - 4*(a*d - b*c)))
    x2 = 0.5 * (a + d - np.sqrt((a+d)**2 - 4*(a*d - b*c)))

    return [x1, x2]

In [448]:
matrix, size = parse_matrix()
mout(matrix)

[[2.3 4.3 5.6 3.2 1.4 2.2]
 [1.4 2.4 5.7 8.4 3.4 5.2]
 [2.5 6.5 4.2 7.1 4.9 9.3]
 [3.8 5.7 2.9 1.6 2.5 7.9]
 [2.4 5.4 3.7 6.2 3.9 1.8]
 [1.8 1.7 3.9 4.6 5.7 5.9]]


In [449]:
w, v = LA.eig(matrix)

In [450]:
mout(w)

[25.56+0.j   -5.64+0.j   -0.67+1.58j -0.67-1.58j  0.87+3.44j  0.87-3.44j]


In [451]:
mout(v)

[[-0.32+0.j   -0.04+0.j    0.75+0.j    0.75-0.j    0.34+0.41j  0.34-0.41j]
 [-0.43+0.j    0.68+0.j   -0.31+0.05j -0.31-0.05j -0.15+0.23j -0.15-0.23j]
 [-0.54+0.j   -0.17+0.j   -0.24+0.36j -0.24-0.36j -0.26+0.06j -0.26-0.06j]
 [-0.38+0.j   -0.68+0.j    0.19-0.3j   0.19+0.3j  -0.09+0.05j -0.09-0.05j]
 [-0.37+0.j    0.1 +0.j   -0.11+0.05j -0.11-0.05j  0.59+0.j    0.59-0.j  ]
 [-0.37+0.j    0.19+0.j   -0.01-0.06j -0.01+0.06j -0.16-0.43j -0.16+0.43j]]


In [452]:
for i in range(size):
    print(f'eigvalue: {np.round(w[i], 2)},\neigvector: {np.round(v[i], 2)}', end='\n'*2)

eigvalue: (25.56+0j),
eigvector: [-0.32+0.j   -0.04+0.j    0.75+0.j    0.75-0.j    0.34+0.41j  0.34-0.41j]

eigvalue: (-5.64+0j),
eigvector: [-0.43+0.j    0.68+0.j   -0.31+0.05j -0.31-0.05j -0.15+0.23j -0.15-0.23j]

eigvalue: (-0.67+1.58j),
eigvector: [-0.54+0.j   -0.17+0.j   -0.24+0.36j -0.24-0.36j -0.26+0.06j -0.26-0.06j]

eigvalue: (-0.67-1.58j),
eigvector: [-0.38+0.j   -0.68+0.j    0.19-0.3j   0.19+0.3j  -0.09+0.05j -0.09-0.05j]

eigvalue: (0.87+3.44j),
eigvector: [-0.37+0.j    0.1 +0.j   -0.11+0.05j -0.11-0.05j  0.59+0.j    0.59-0.j  ]

eigvalue: (0.87-3.44j),
eigvector: [-0.37+0.j    0.19+0.j   -0.01-0.06j -0.01+0.06j -0.16-0.43j -0.16+0.43j]



In [453]:
matrix@v[0]

array([ 6.93870824-0.32981673j, 12.98418772-0.74208764j,
       12.24559892-1.81399202j,  5.45572935-2.22626293j,
        8.39972815+0.86576892j,  9.67580613-0.08245418j])

In [454]:
v[0]*w[0]

array([-8.16166221 +0.j       , -1.03338675 +0.j       ,
       19.26347578 +0.j       , 19.26347578 +0.j       ,
        8.62067721+10.5367091j,  8.62067721-10.5367091j])

In [455]:
hess_matrix = hessenberg(matrix)
mout(hess_matrix)

[[ 2.3  -7.02 -3.41 -1.93  1.48 -0.11]
 [-5.63 20.97  6.73 -2.79  0.49 -5.68]
 [ 0.   10.75 -1.87  0.67  0.44 -0.41]
 [ 0.   -0.    2.14 -1.41  1.46 -3.42]
 [-0.   -0.    0.   -1.82 -0.15  1.72]
 [ 0.   -0.    0.   -0.   -3.83  0.47]]


In [456]:
mout(scipy_hessenberg(matrix))

[[ 2.3  -7.02 -3.41 -1.93  1.48 -0.11]
 [-5.63 20.97  6.73 -2.79  0.49 -5.68]
 [ 0.   10.75 -1.87  0.67  0.44 -0.41]
 [ 0.    0.    2.14 -1.41  1.46 -3.42]
 [ 0.    0.    0.   -1.82 -0.15  1.72]
 [ 0.    0.    0.    0.   -3.83  0.47]]


In [469]:
eig_approx = hess_matrix
for i in range(20):
    m = eig_approx
    Q, R = LA.qr(m)
    eig_approx = R@Q
    if i % 5 == 0:
        print('iteration: ', i)
        print('A matrix: ')
        mout(eig_approx)
    
my_w = np.array([eig_approx[0, 0],
        eig_approx[1, 1],
        *get_eig_vals(eig_approx[2:4, 2:4]),
        *get_eig_vals(eig_approx[4:, 4:]),
       ])
print('final A: ')
mout(eig_approx)
print('My eig values')
mout(my_w)
print('Scipy eig values')
mout(w)

iteration:  0
A matrix: 
[[ 22.72  -7.82   2.11  -1.13   5.24  -0.54]
 [-10.04  -1.38  -0.43   4.05  -1.09  -1.39]
 [ -0.     2.15  -0.85   0.23  -2.6    1.97]
 [ -0.     0.    -3.55   0.2   -1.05   1.82]
 [  0.     0.     0.    -2.     0.27  -3.6 ]
 [  0.    -0.     0.     0.     2.56  -0.66]]
iteration:  5
A matrix: 
[[25.56  1.1   0.31  4.75 -4.44 -2.18]
 [ 0.   -5.63  0.1   0.49  0.86 -3.13]
 [ 0.    0.22 -0.44  4.06  0.39 -2.03]
 [ 0.   -0.   -3.32  2.12 -0.42 -0.1 ]
 [ 0.   -0.   -0.    0.11 -0.83  0.84]
 [-0.   -0.    0.    0.   -2.85 -0.47]]
iteration:  10
A matrix: 
[[ 2.556e+01  1.020e+00  1.560e+00 -4.420e+00  1.880e+00 -4.670e+00]
 [-0.000e+00 -5.640e+00  3.000e-02 -1.800e-01 -2.660e+00 -1.740e+00]
 [-0.000e+00  2.000e-02 -2.600e-01  3.030e+00  1.690e+00  1.080e+00]
 [-0.000e+00 -0.000e+00 -4.330e+00  1.990e+00  5.600e-01  9.700e-01]
 [ 0.000e+00  0.000e+00  0.000e+00 -0.000e+00  2.600e-01 -1.570e+00]
 [ 0.000e+00 -0.000e+00  0.000e+00  0.000e+00  2.150e+00 -1.610e+00]]
ite

In [458]:
x0 = np.ones(size, dtype=np.float64)
lmd = 2 * LA.eigvals(matrix)[0]/3;
e = 0.1
k = 0
m = matrix - lmd*np.eye(size)
m_inv = LA.inv(m)
y = m_inv@x0
x = y / LA.norm(y)
while (LA.norm(x0-x)>e):
    x0 = x.copy()
    y = m_inv@x0
    x = y / LA.norm(y)
    k += 1
    
mout(x)
print(k)

[0.32+0.j 0.43+0.j 0.55+0.j 0.37+0.j 0.37+0.j 0.36+0.j]
2


In [459]:
np.sqrt(-5)

C:\Users\vikto\AppData\Local\Temp\ipykernel_4384\2416034784.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-5)


nan