In [45]:
import numpy as np
from numpy import linalg as LA

In [46]:
f_name = 'matrix.txt'

In [47]:
def parse_matrix(f_name=f_name):
    with open(f_name, 'r') as f:
            matrix = f.read().split('\n')
            matrix = list(map(lambda row: row.split(' '), matrix))
            return np.array(matrix, dtype=np.float64), len(matrix)

In [48]:
matrix, size = parse_matrix()
matrix

array([[2.3, 4.3, 5.6, 3.2, 1.4, 2.2],
       [1.4, 2.4, 5.7, 8.4, 3.4, 5.2],
       [2.5, 6.5, 4.2, 7.1, 4.9, 9.3],
       [3.8, 5.7, 2.9, 1.6, 2.5, 7.9],
       [2.4, 5.4, 3.7, 6.2, 3.9, 1.8],
       [1.8, 1.7, 3.9, 4.6, 5.7, 5.9]])

In [49]:
w, v = LA.eig(matrix)

In [50]:
w

array([25.55773101+0.j        , -5.64128031+0.j        ,
       -0.67376672+1.58344078j, -0.67376672-1.58344078j,
        0.86554137+3.44262511j,  0.86554137-3.44262511j])

In [51]:
v

array([[-0.31934221+0.j        , -0.04043343+0.j        ,
         0.75372402+0.j        ,  0.75372402-0.j        ,
         0.33730213+0.41227091j,  0.33730213-0.41227091j],
       [-0.42838892+0.j        ,  0.67772387+0.j        ,
        -0.30991418+0.05047081j, -0.30991418-0.05047081j,
        -0.14924022+0.23251143j, -0.14924022-0.23251143j],
       [-0.54125353+0.j        , -0.17208063+0.j        ,
        -0.24081114+0.35875139j, -0.24081114-0.35875139j,
        -0.25969285+0.06304831j, -0.25969285-0.06304831j],
       [-0.37944822+0.j        , -0.68154322+0.j        ,
         0.19175006-0.30435226j,  0.19175006+0.30435226j,
        -0.08701143+0.05229136j, -0.08701143-0.05229136j],
       [-0.37412222+0.j        ,  0.10104957+0.j        ,
        -0.10716492+0.0482279j , -0.10716492-0.0482279j ,
         0.58818811+0.j        ,  0.58818811-0.j        ],
       [-0.37094436+0.j        ,  0.1863641 +0.j        ,
        -0.01081607-0.05733943j, -0.01081607+0.05733943j,
        -

In [60]:
for i in range(size):
    print(f'eigvalue: {np.round(w[i], 3)},\neigvector: {np.round(v[i], 3)}', end='\n'*2)

eigvalue: (25.558+0j),
eigvector: [-0.319+0.j    -0.04 +0.j     0.754+0.j     0.754-0.j     0.337+0.412j
  0.337-0.412j]

eigvalue: (-5.641+0j),
eigvector: [-0.428+0.j     0.678+0.j    -0.31 +0.05j  -0.31 -0.05j  -0.149+0.233j
 -0.149-0.233j]

eigvalue: (-0.674+1.583j),
eigvector: [-0.541+0.j    -0.172+0.j    -0.241+0.359j -0.241-0.359j -0.26 +0.063j
 -0.26 -0.063j]

eigvalue: (-0.674-1.583j),
eigvector: [-0.379+0.j    -0.682+0.j     0.192-0.304j  0.192+0.304j -0.087+0.052j
 -0.087-0.052j]

eigvalue: (0.866+3.443j),
eigvector: [-0.374+0.j     0.101+0.j    -0.107+0.048j -0.107-0.048j  0.588+0.j
  0.588-0.j   ]

eigvalue: (0.866-3.443j),
eigvector: [-0.371+0.j     0.186+0.j    -0.011-0.057j -0.011+0.057j -0.16 -0.432j
 -0.16 +0.432j]



1