In [333]:
import numpy as np

In [334]:
def gauss_jordano(a, b):
    system = np.column_stack((a, b))
    length = len(a)

    for i in range(length):
        if system[i, i] == 0.:
            system[i, :], system[(i+1) % length, :] = system[(i+1) % length, :].copy(), system[i, :].copy()

        system[i, :] = system[i, :] / system[i, i]

        for j in range(i + 1, length):
            system[j, :] = system[j, :] - system[i, :] * system[j, i]

    for i in range(length - 1, 0, -1):
        for j in range(i - 1, -1, -1):
            system[j, :] = system[j, :] - system[i, :] * system[j, i]

    return np.array(system[:, -1])

In [335]:
size = 18

In [336]:
a = np.arange(1, size+1)
A = np.array([a * np.concatenate((np.ones(i)*-1, np.ones(size-i))) for i in range(size)], dtype=float)
A[range(size), range(size)] = 0
A[0, 0] = 1

b = np.arange(1, size+1, dtype=float)

In [337]:
A

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [-1.,  0.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [-1., -2.,  0.,  4.,  5.,  6.,  7.,  8.,  9.],
       [-1., -2., -3.,  0.,  5.,  6.,  7.,  8.,  9.],
       [-1., -2., -3., -4.,  0.,  6.,  7.,  8.,  9.],
       [-1., -2., -3., -4., -5.,  0.,  7.,  8.,  9.],
       [-1., -2., -3., -4., -5., -6.,  0.,  8.,  9.],
       [-1., -2., -3., -4., -5., -6., -7.,  0.,  9.],
       [-1., -2., -3., -4., -5., -6., -7., -8.,  0.]])

In [338]:
b

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [339]:
print(*np.round(x := gauss_jordano(A, b), 3), sep='\n')

5.0
-5.5
3.333
-2.75
2.0
-1.833
1.429
-1.375
1.111


In [340]:
np.random.seed(42)
noise_for_A = np.random.normal(0, 0.292, (size, size))
delta_A = np.linalg.norm(noise_for_A, ord=np.inf) / np.linalg.norm(A, ord=np.inf)
A_noise = A + noise_for_A
delta_A*100

5.0140768975811705

In [341]:
np.round(A_noise, 3)

array([[ 1.145,  1.96 ,  3.189,  4.445,  4.932,  5.932,  7.461,  8.224,
         8.863],
       [-0.842, -0.135,  2.864,  4.071,  4.441,  5.496,  6.836,  7.704,
         9.092],
       [-1.265, -2.412,  0.428,  3.934,  5.02 ,  5.584,  6.841,  8.032,
         8.664],
       [-0.89 , -2.175, -3.085, -0.176,  5.541,  5.996,  6.691,  8.24 ,
         8.644],
       [-0.939, -2.572, -3.388, -3.943,  0.216,  6.05 ,  6.966,  7.912,
         8.568],
       [-1.21 , -2.135, -2.691, -3.9  , -5.515,  0.095,  6.888,  7.802,
         9.179],
       [-0.699, -1.728, -3.245, -4.09 , -4.903, -5.715, -0.14 ,  7.946,
         8.677],
       [-1.349, -1.763, -2.604, -4.021, -4.707, -5.894, -7.188,  0.106,
         9.449],
       [-1.01 , -1.543, -3.765, -3.76 , -4.975, -6.087, -6.973, -8.58 ,
        -0.064]])

In [342]:
np.random.seed(42)
noise_for_b = np.random.normal(0, 0.286, size)
delta_b = np.linalg.norm(noise_for_b, ord=np.inf) / np.linalg.norm(b, ord=np.inf)
b_noise = b + noise_for_b
delta_b*100

5.018387391501266

In [343]:
np.round(b_noise, 3)

array([1.142, 1.96 , 3.185, 4.436, 4.933, 5.933, 7.452, 8.219, 8.866])

In [344]:
print(np.round(x1 := gauss_jordano(A_noise, b), 3))
print(np.round(x2 := gauss_jordano(A, b_noise), 3))
print(np.round(x3 := gauss_jordano(A_noise, b_noise), 3))

[ 8.894 -9.108  7.075 -6.197  4.708 -4.776  3.74  -3.242  1.977]
[ 5.029 -5.438  3.217 -2.726  2.081 -1.901  1.412 -1.332  1.112]
[ 8.558 -8.679  6.619 -5.865  4.547 -4.632  3.567 -3.078  1.925]


In [345]:
print("A norm 1: ", round(np.linalg.cond(A, p=1), 3))
print("A norm 2: ", round(np.linalg.cond(A, p=2), 3))
print("A euklidian norm", round(np.linalg.cond(A, p="fro"), 3))
print("A norm inf: ", round(np.linalg.cond(A, p=np.inf), 3))

A norm 1:  327.371
A norm 2:  178.965
A euklidian norm 225.006
A norm inf:  405.0


In [346]:
print("A_noise norm 1: ", round(np.linalg.cond(A_noise, p=1), 3))
print("A_noise norm 2: ", round(np.linalg.cond(A_noise, p=2), 3))
print("A_noise euklid norm", round(np.linalg.cond(A_noise, p="fro"), 3))
print("A_noise norm inf: ", round(np.linalg.cond(A_noise, p=np.inf), 3))

A_noise norm 1:  733.295
A_noise norm 2:  344.447
A_noise euklid norm 429.469
A_noise norm inf:  571.355


In [347]:
print(dx1 := np.linalg.norm(x1 - x, ord=np.inf))
print(dx2 := np.linalg.norm(x2 - x, ord=np.inf))
print(dx3 := np.linalg.norm(x3 - x, ord=np.inf))

3.8944006564090046
0.1160285275114159
3.558447646704453


In [348]:
print(delta_x1 := dx1/np.linalg.norm(x, ord=np.inf))
print(delta_x2 := dx2/np.linalg.norm(x, ord=np.inf))
print(delta_x3 := dx3/np.linalg.norm(x, ord=np.inf))

0.7080728466198197
0.021096095911166547
0.646990481218992


In [349]:
relx = np.linalg.norm(np.linalg.inv(A), ord=np.inf) * np.linalg.norm(b, ord=np.inf) / np.linalg.norm(x, ord=np.inf)
relx

14.727272727272739

In [350]:
print(round(relx * delta_b, 3))
print(round(np.linalg.cond(A_noise, p=np.inf) * delta_A, 3))
print(round(np.linalg.cond(A_noise, p=np.inf) * (delta_A + delta_b), 3))

0.739
28.648
57.321


In [351]:
print(round(delta_x1/ delta_b, 3))
print(round(delta_x2/ delta_A, 3))
print(round(delta_x3/(delta_A + delta_b), 3))

14.11
0.421
6.449
