In [370]:
import numpy as np

In [371]:
def gauss_solve(a, b):
    x = np.zeros(len(a))
    size = len(a)

    for i in range(size):
        print(f'iterarion: {i + 1}')
        
        per = np.eye(size)
        idx = i + np.argmax(np.abs(a[i:, i]))
        per[i, :], per[idx, :] = per[idx, :].copy(), per[i, :].copy()
        a, b = per@a, per@b
        print(f'permutation matrix:\n{np.round(per, 3)}')
        
        m = np.eye(size)
        m[i+1:, i] = -a[i+1:, i] / a[i, i]
        m[range(size), range(size)] = 1
        m[i, i] = m[i, i] / a[i, i]
        print(f'M matrix:\n{np.round(m, 3)}')
        a, b = m@a, m@b
        print(f'a matrix:\n{np.round(a, 3)}', end='\n'*2)
        
    system = np.column_stack((a, b))
    for i in range(size - 1, -1, -1):
        x[size - i - 1] = b[i] - x[::-1]@a[i]

    return x[::-1]

In [372]:
def LU_det(a):
    
    size = len(a)
    
    u = np.zeros((size, size))
    l = np.eye(size)
    
    for i in range(size):
        for j in range(size):
            if i <= j:
                u[i, j] = a[i, j] - l[:, i]@u[i, :]
            else:
                l[i, j] = (a[i, j] - l[:, i]@u[i, :]) / u[j, j]
    return l, u

In [373]:
size = 5

In [374]:
a = np.arange(1, size+1)
A = np.array([a * np.concatenate((np.ones(i)*-1, np.ones(size-i))) for i in range(size)], dtype=float)
A[range(size), range(size)] = 0
A[0, 0] = 1

b = np.arange(1, size+1, dtype=float)

In [375]:
# A = np.random.rand(5, 5)
A

array([[ 1.,  2.,  3.,  4.,  5.],
       [-1.,  0.,  3.,  4.,  5.],
       [-1., -2.,  0.,  4.,  5.],
       [-1., -2., -3.,  0.,  5.],
       [-1., -2., -3., -4.,  0.]])

In [376]:
# b = np.random.rand(5)
b

array([1., 2., 3., 4., 5.])

In [377]:
x = gauss_solve(A, b)

iterarion: 1
permutation matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
M matrix:
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]
a matrix:
[[ 1.  2.  3.  4.  5.]
 [ 0.  2.  6.  8. 10.]
 [ 0.  0.  3.  8. 10.]
 [ 0.  0.  0.  4. 10.]
 [ 0.  0.  0.  0.  5.]]

iterarion: 2
permutation matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
M matrix:
[[ 1.   0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.   0. ]
 [ 0.  -0.   1.   0.   0. ]
 [ 0.  -0.   0.   1.   0. ]
 [ 0.  -0.   0.   0.   1. ]]
a matrix:
[[ 1.  2.  3.  4.  5.]
 [ 0.  1.  3.  4.  5.]
 [ 0.  0.  3.  8. 10.]
 [ 0.  0.  0.  4. 10.]
 [ 0.  0.  0.  0.  5.]]

iterarion: 3
permutation matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
M matrix:
[[ 1.     0.     0.     0.     0.   ]
 [ 0.     1.     0.     0.     0.   ]
 [ 0.     0.     0.333  0.     0.   

In [378]:
x

array([ 3.  , -3.5 ,  2.  , -1.75,  1.2 ])

In [379]:
np.linalg.solve(A, b)

array([ 3.  , -3.5 ,  2.  , -1.75,  1.2 ])

In [380]:
l, u = LU_det(A)

C:\Users\vikto\AppData\Local\Temp\ipykernel_320\2222505529.py:13: RuntimeWarning: divide by zero encountered in double_scalars
  l[i, j] = (a[i, j] - l[:, i]@u[i, :]) / u[j, j]


In [381]:
l

array([[  1.,   0.,   0.,   0.,   0.],
       [ -1.,   1.,   0.,   0.,   0.],
       [ -1., -inf,   1.,   0.,   0.],
       [ -1., -inf, -inf,   1.,   0.],
       [ -1., -inf, -inf, -inf,   1.]])

In [382]:
u

array([[1., 1., 2., 3., 4.],
       [0., 0., 3., 4., 5.],
       [0., 0., 0., 4., 5.],
       [0., 0., 0., 0., 5.],
       [0., 0., 0., 0., 0.]])

In [383]:
l@u

C:\Users\vikto\AppData\Local\Temp\ipykernel_320\2306406285.py:1: RuntimeWarning: invalid value encountered in matmul
  l@u


array([[  1.,   1.,   2.,   3.,   4.],
       [ -1.,  -1.,   1.,   1.,   1.],
       [ nan,  nan, -inf, -inf, -inf],
       [ nan,  nan,  nan, -inf, -inf],
       [ nan,  nan,  nan,  nan, -inf]])