In [319]:
import numpy as np

In [320]:
def gauss_jordano_inv(a):
    size = len(a)
    a_inv = np.eye(size)

    for i in range(size):
        print(f'iterarion: {i + 1}')
        
        per = np.eye(size)
        idx = i + np.argmax(np.abs(a[i:, i]))
        per[i, :], per[idx, :] = per[idx, :].copy(), per[i, :].copy()
        a, a_inv = a@per, a_inv@per
        print(f'permutation matrix:\n{np.round(per, 3)}')
        
        m = np.eye(size)
        m[i+1:, i] = -a[i+1:, i] / a[i, i]
        m[range(size), range(size)] = 1
        m[i, i] = m[i, i] / a[i, i]
        print(f'M matrix:\n{np.round(m, 3)}')
        
        a, a_inv = m@a, m@a_inv
        print(f'a matrix:\n{np.round(a, 3)}')
        print(f'inv a matrix:\n{np.round(a_inv, 3)}', end='\n'*2)
        

    for i in range(1, size):
        print(f'iterarion: {size + i}')
        
        m = np.eye(size)
        m[:i, i] = -a[:i, i]
        print(f'M matrix:\n{np.round(m, 3)}')
        
        a, a_inv = m@a, m@a_inv
        print(f'a matrix:\n{np.round(a, 3)}')
        print(f'inv a matrix:\n{np.round(a_inv, 3)}', end='\n'*2)

    return a_inv

In [321]:
def gauss_solve(a, b):
    x = np.zeros(len(a))
    size = len(a)

    for i in range(size):
        print(f'iterarion: {i + 1}')
        
        per = np.eye(size)
        idx = i + np.argmax(np.abs(a[i:, i]))
        per[i, :], per[idx, :] = per[idx, :].copy(), per[i, :].copy()
        a, b = per@a, per@b
        print(f'permutation matrix:\n{np.round(per, 3)}')
        
        m = np.eye(size)
        m[i+1:, i] = -a[i+1:, i] / a[i, i]
        m[range(size), range(size)] = 1
        m[i, i] = m[i, i] / a[i, i]
        print(f'M matrix:\n{np.round(m, 3)}')
        
        a, b = m@a, m@b
        print(f'a matrix:\n{np.round(a, 3)}', end='\n'*2)
        
    system = np.column_stack((a, b))
    for i in range(size - 1, -1, -1):
        x[size - i - 1] = b[i] - x[::-1]@a[i]

    return x[::-1]

In [322]:
size = 5

In [323]:
a = np.arange(1, size+1)
A = np.array([a * np.concatenate((np.ones(i)*-1, np.ones(size-i))) for i in range(size)], dtype=float)
A[range(size), range(size)] = 0
A[0, 0] = 1

b = np.arange(1, size+1, dtype=float)

In [324]:
A = np.random.rand(5, 5)
A

array([[0.51211624, 0.64316715, 0.6309514 , 0.91469165, 0.18532878],
       [0.04675873, 0.19450478, 0.72958043, 0.40122078, 0.55515513],
       [0.31090653, 0.23641181, 0.49430789, 0.9858978 , 0.66572805],
       [0.5577105 , 0.97804998, 0.60325354, 0.74669856, 0.07205606],
       [0.7047245 , 0.93718566, 0.18956435, 0.0147458 , 0.33992423]])

In [325]:
b = np.random.rand(5)
b

array([0.58975256, 0.14260403, 0.71969246, 0.17343698, 0.19856953])

In [326]:
x = gauss_solve(A, b)

iterarion: 1
permutation matrix:
[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
M matrix:
[[ 1.419  0.     0.     0.     0.   ]
 [-0.066  1.     0.     0.     0.   ]
 [-0.441  0.     1.     0.     0.   ]
 [-0.791  0.     0.     1.     0.   ]
 [-0.727  0.     0.     0.     1.   ]]
a matrix:
[[ 1.     1.33   0.269  0.021  0.482]
 [ 0.     0.132  0.717  0.4    0.533]
 [ 0.    -0.177  0.411  0.979  0.516]
 [ 0.     0.236  0.453  0.735 -0.197]
 [ 0.    -0.038  0.493  0.904 -0.062]]

iterarion: 2
permutation matrix:
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
M matrix:
[[ 1.     0.     0.     0.     0.   ]
 [ 0.     4.231  0.     0.     0.   ]
 [ 0.     0.749  1.     0.     0.   ]
 [ 0.    -0.56   0.     1.     0.   ]
 [ 0.     0.16   0.     0.     1.   ]]
a matrix:
[[ 1.     1.33   0.269  0.021  0.482]
 [ 0.     1.     1.917  3.11  -0.833]
 [ 0.     0.     0.75   1.53   0.368]
 [ 0.     0.     0.463 -

In [327]:
x

array([ 1.99644878e+00, -1.34778242e+00,  2.68301975e-01,  2.89840430e-01,
       -1.14408016e-03])

In [328]:
np.linalg.solve(A, b)

array([ 1.99644878e+00, -1.34778242e+00,  2.68301975e-01,  2.89840430e-01,
       -1.14408016e-03])

In [329]:
inv_A = gauss_jordano_inv(A)

iterarion: 1
permutation matrix:
[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
M matrix:
[[ 5.396  0.     0.     0.     0.   ]
 [-2.996  1.     0.     0.     0.   ]
 [-3.592  0.     1.     0.     0.   ]
 [-0.389  0.     0.     1.     0.   ]
 [-1.834  0.     0.     0.     1.   ]]
a matrix:
[[ 1.     3.47   3.404  4.936  2.763]
 [ 0.    -1.732 -1.16  -2.339 -1.487]
 [ 0.    -2.074 -1.772 -2.3   -1.529]
 [ 0.     0.728  0.358  0.391  0.359]
 [ 0.    -0.242 -0.968 -1.663 -0.235]]
inv a matrix:
[[ 0.     0.     0.     0.     5.396]
 [ 0.     1.     0.     0.    -2.996]
 [ 0.     0.     1.     0.    -3.592]
 [ 0.     0.     0.     1.    -0.389]
 [ 1.     0.     0.     0.    -1.834]]

iterarion: 2
permutation matrix:
[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
M matrix:
[[ 1.     0.     0.     0.     0.   ]
 [ 0.    -0.862  0.     0.     0.   ]
 [ 0.    -1.527  1.     0.     0.   ]
 [ 0.     0.308  0. 

In [330]:
inv_A

array([[ 0.49955982,  1.56106577, -2.33395246,  0.32280318,  0.61459038],
       [ 0.09937682, -2.13406886,  3.21405893,  1.68863907, -2.02877255],
       [ 1.82784641, -1.90192201,  6.87045361, -0.38798135, -5.73261141],
       [-0.49544309,  1.27477729, -4.95390239, -0.15264816,  4.47710029],
       [-0.8447676 ,  1.32426441, -1.01416693, -0.90566484,  1.33640137]])

In [331]:
np.linalg.inv(A)

array([[ 6.87045361, -0.38798135, -1.90192201, -5.73261141,  1.82784641],
       [-4.95390239, -0.15264816,  1.27477729,  4.47710029, -0.49544309],
       [ 3.21405893,  1.68863907, -2.13406886, -2.02877255,  0.09937682],
       [-1.01416693, -0.90566484,  1.32426441,  1.33640137, -0.8447676 ],
       [-2.33395246,  0.32280318,  1.56106577,  0.61459038,  0.49955982]])