In [131]:
import numpy as np

In [132]:
def gauss_jordano(a, b):
    size = len(a)
    system = np.column_stack((a, b))

    for i in range(size):
        if system[i, i] == 0.:
            system[i, :], system[(i+1) % size, :] = system[(i+1) % size, :].copy(), system[i, :].copy()

        system[i, :] = system[i, :] / system[i, i]

        for j in range(i + 1, size):
            system[j, :] = system[j, :] - system[i, :] * system[j, i]

    for i in range(size - 1, 0, -1):
        for j in range(i - 1, -1, -1):
            system[j, :] = system[j, :] - system[i, :] * system[j, i]

    return np.array(system[:, -1])

In [133]:
def gauss(a, b):
    x = np.zeros(len(a))
    size = len(a)

    for i in range(size):
        print(f'iterarion: {i + 1}')
        
        per = np.eye(size)
        idx = i + np.argmax(np.abs(a[i:, i]))
        per[i, :], per[idx, :] = per[idx, :].copy(), per[i, :].copy()
        a, b = per@a, per@b
        print(f'permutation matrix:\n{per}')
        
        m = np.eye(size)
        m[i+1:, i] = -a[i+1:, i] / a[i, i]
        m[range(size), range(size)] = 1
        m[i, i] = m[i, i] / a[i, i]
        print(f'M matrix:\n{m}')
        
        a, b = m@a, m@b
        print(f'a matrix:\n{a}', end='\n'*2)
        
    system = np.column_stack((a, b))
    for i in range(size - 1, -1, -1):
        x[len(a) - i - 1] = system[i, -1] - x[::-1]@system[i, :-1]

    return x[::-1]

In [134]:
size = 5

In [135]:
a = np.arange(1, size+1)
A = np.array([a * np.concatenate((np.ones(i)*-1, np.ones(size-i))) for i in range(size)], dtype=float)
A[range(size), range(size)] = 0
A[0, 0] = 1

b = np.arange(1, size+1, dtype=float)

In [136]:
A = np.random.rand(5, 5)
A

array([[0.83866794, 0.7682857 , 0.81241828, 0.46603133, 0.75196593],
       [0.22369958, 0.42325557, 0.45523347, 0.69268756, 0.98350213],
       [0.33133265, 0.18839091, 0.48871242, 0.15554205, 0.81361784],
       [0.57120008, 0.35878418, 0.45049912, 0.97627326, 0.78985204],
       [0.05223803, 0.7796463 , 0.24068789, 0.19735126, 0.67742994]])

In [137]:
b = np.random.rand(5)
b

array([0.6702737 , 0.10043313, 0.64528839, 0.1533425 , 0.23094578])

In [138]:
gauss(A, b)

iterarion: 1
permutation matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
M matrix:
[[ 1.19236703  0.          0.          0.          0.        ]
 [-0.26673201  1.          0.          0.          0.        ]
 [-0.39507013  0.          1.          0.          0.        ]
 [-0.68108015  0.          0.          1.          0.        ]
 [-0.06228691  0.          0.          0.          1.        ]]
a matrix:
[[ 1.          0.91607854  0.96870076  0.5556804   0.89661938]
 [ 0.          0.21832918  0.23853552  0.56838209  0.78292875]
 [ 0.         -0.11513582  0.16775023 -0.02857301  0.51653856]
 [ 0.         -0.16447995 -0.10282284  0.65886857  0.27770297]
 [ 0.          0.73179216  0.19008487  0.16832361  0.63059231]]

iterarion: 2
permutation matrix:
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]
M matrix:
[[ 1.          0.          0.          0.          0.        ]
 [ 0.          1.36650822 

array([ 1.50792473, -0.08985058, -0.94597394, -1.03751336,  0.96639583])

In [139]:
gauss_jordano(A, b)

array([ 1.50792473, -0.08985058, -0.94597394, -1.03751336,  0.96639583])

In [140]:
np.linalg.solve(A, b)

array([ 1.50792473, -0.08985058, -0.94597394, -1.03751336,  0.96639583])