In [200]:
import numpy as np
from numpy import linalg as LA
from scipy.linalg import lu as LU

In [201]:
def gauss_solve(a, b, out=True):
    size = len(a)
    x = np.zeros(size)

    for i in range(size):
        
        per = np.eye(size)
        idx = i + np.argmax(np.abs(a[i:, i]))
        per[i, :], per[idx, :] = per[idx, :].copy(), per[i, :].copy()
        a, b = per@a, per@b
        
        m = np.eye(size)
        m[i+1:, i] = -a[i+1:, i] / a[i, i]
        m[range(size), range(size)] = 1
        m[i, i] = m[i, i] / a[i, i]
        
        a, b = m@a, m@b
        
        if out:
            print(f'iterarion: {i + 1}')
            print(f'permutation matrix:\n{np.round(per, 3)}')
            print(f'M matrix:\n{np.round(m, 3)}')
            print(f'a matrix:\n{np.round(a, 3)}', end='\n'*2)
        
    system = np.column_stack((a, b))
    for i in range(size - 1, -1, -1):
        x[size - i - 1] = b[i] - x[::-1]@a[i]

    return x[::-1]

In [202]:
def gauss_inv(a):
    size = len(a)
    b = np.eye(size)
    x = np.zeros((size, size))
    
    for i in range(size):
        
        per = np.eye(size)
        idx = i + np.argmax(np.abs(a[i:, i]))
        per[i, :], per[idx, :] = per[idx, :].copy(), per[i, :].copy()
        a, b = per@a, per@b
        
        m = np.eye(size)
        m[i+1:, i] = -a[i+1:, i] / a[i, i]
        m[range(size), range(size)] = 1
        m[i, i] = m[i, i] / a[i, i]
        
        a, b = m@a, m@b
        
    system = np.column_stack((a, b))
    for i in range(size - 1, -1, -1):
        x[:, i] = b[i] - x@a[i]

    return x.T

In [203]:
def run_through_method(a, b):
    
    size = len(a)
    x = np.zeros(size)
    
    v, u = np.zeros(size), np.zeros(size)

    v[0] = a[0][1] / (-a[0][0]) 
    u[0] = (- b[0]) / (-a[0][0]) 
    for i in range(1, size - 1): 
        v[i] = a[i][i+1] / (-a[i][i] - a[i][i-1]*v[i-1])
        u[i] = (a[i][i-1]*u[i-1] - b[i]) / (-a[i][i] - a[i][i-1]*v[i-1])
        
    v[size-1] = 0
    u[size-1] = (a[size-1][size-2]*u[size-2] - b[size-1]) / (-a[size-1][size-1] - a[size-1][size-2]*v[size-2])
    
    x[size-1] = u[size-1]
    for i in range(size-1, 0, -1):
        x[i-1] = v[i-1] * x[i] + u[i-1]
        
    return x

In [204]:
size = 5

In [205]:
a = np.arange(1, size+1)
A = np.array([a * np.concatenate((np.ones(i)*-1, np.ones(size-i))) for i in range(size)], dtype=float)
A[range(size), range(size)] = 0
A[0, 0] = 1

b = np.arange(1, size+1, dtype=float)

In [206]:
# A = np.random.rand(5, 5)
A

array([[ 1.,  2.,  3.,  4.,  5.],
       [-1.,  0.,  3.,  4.,  5.],
       [-1., -2.,  0.,  4.,  5.],
       [-1., -2., -3.,  0.,  5.],
       [-1., -2., -3., -4.,  0.]])

In [207]:
# b = np.random.rand(5, 5)
b

array([1., 2., 3., 4., 5.])

In [208]:
x = gauss_solve(A, b)

iterarion: 1
permutation matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
M matrix:
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]
a matrix:
[[ 1.  2.  3.  4.  5.]
 [ 0.  2.  6.  8. 10.]
 [ 0.  0.  3.  8. 10.]
 [ 0.  0.  0.  4. 10.]
 [ 0.  0.  0.  0.  5.]]

iterarion: 2
permutation matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
M matrix:
[[ 1.   0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.   0. ]
 [ 0.  -0.   1.   0.   0. ]
 [ 0.  -0.   0.   1.   0. ]
 [ 0.  -0.   0.   0.   1. ]]
a matrix:
[[ 1.  2.  3.  4.  5.]
 [ 0.  1.  3.  4.  5.]
 [ 0.  0.  3.  8. 10.]
 [ 0.  0.  0.  4. 10.]
 [ 0.  0.  0.  0.  5.]]

iterarion: 3
permutation matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
M matrix:
[[ 1.     0.     0.     0.     0.   ]
 [ 0.     1.     0.     0.     0.   ]
 [ 0.     0.     0.333  0.     0.   

In [209]:
x

array([ 3.  , -3.5 ,  2.  , -1.75,  1.2 ])

In [210]:
np.linalg.solve(A, b)

array([ 3.  , -3.5 ,  2.  , -1.75,  1.2 ])

In [211]:
P, L, U = LU(A)

In [212]:
P

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [213]:
L

array([[ 1.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  0.,  0.,  0.],
       [-1.,  0.,  1.,  0.,  0.],
       [-1.,  0.,  0.,  1.,  0.],
       [-1.,  0.,  0.,  0.,  1.]])

In [214]:
U

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 0.,  2.,  6.,  8., 10.],
       [ 0.,  0.,  3.,  8., 10.],
       [ 0.,  0.,  0.,  4., 10.],
       [ 0.,  0.,  0.,  0.,  5.]])

In [215]:
LA.det(U)/LA.det(P)

119.99999999999997

In [216]:
U[range(size), range(size)].prod()/LA.det(P)

120.0

In [217]:
LA.det(A)

119.99999999999997

In [218]:
gauss_inv(A)

array([[ 1.        , -1.        ,  1.        , -1.        ,  1.        ],
       [-0.5       ,  0.5       , -1.        ,  1.        , -1.        ],
       [ 0.33333333,  0.        ,  0.33333333, -0.66666667,  0.66666667],
       [-0.25      ,  0.        ,  0.        ,  0.25      , -0.5       ],
       [ 0.2       ,  0.        ,  0.        ,  0.        ,  0.2       ]])

In [219]:
LA.inv(A)

array([[ 1.        , -1.        ,  1.        , -1.        ,  1.        ],
       [-0.5       ,  0.5       , -1.        ,  1.        , -1.        ],
       [ 0.33333333,  0.        ,  0.33333333, -0.66666667,  0.66666667],
       [-0.25      ,  0.        ,  0.        ,  0.25      , -0.5       ],
       [ 0.2       ,  0.        ,  0.        ,  0.        ,  0.2       ]])

In [220]:
size = 10

In [221]:
k1 = np.arange(1, size+1)
k2 = np.arange(1, size-1)

A = np.diag(k1/5)
A[np.arange(size-2), np.arange(size-2) + 1] = 5*k2
A[np.arange(size-2) + 1, np.arange(size-2)] = k2 - 5
d = k1**2 / 5 + k1*5

In [222]:
A

array([[ 0.2,  5. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [-4. ,  0.4, 10. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -3. ,  0.6, 15. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. , -2. ,  0.8, 20. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , -1. ,  1. , 25. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  1.2, 30. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  1.4, 35. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  2. ,  1.6, 40. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  3. ,  1.8,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  2. ]])

In [223]:
d

array([ 5.2, 10.8, 16.8, 23.2, 30. , 37.2, 44.8, 52.8, 61.2, 70. ])

In [224]:
(np.abs(A[range(1,size-1), range(1,size-1)]) >=
    np.abs(A[np.arange(size-2), np.arange(size-2) + 1]) +
    np.abs(A[np.arange(size-2) + 1, np.arange(size-2)])).all()

False

In [225]:
run_through_method(A, d)

array([ 2.82010400e+05, -1.12793760e+04,  1.13256415e+05, -6.78501179e+03,
        1.15982020e+04, -7.34128550e+02,  3.06051420e+01,  2.10308958e+01,
       -1.05149293e+00,  3.50000000e+01])

In [226]:
LA.solve(A, d)

array([ 2.82010400e+05, -1.12793760e+04,  1.13256415e+05, -6.78501179e+03,
        1.15982020e+04, -7.34128550e+02,  3.06051420e+01,  2.10308958e+01,
       -1.05149293e+00,  3.50000000e+01])